### ISSUE TITLE
Need to change the API to make events order in natural order: Nearest upcoming first and then most recent past event first

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/events.eclipse.org#169]
This is to for: https://deploy-preview-111--eclipsefdn-events.netlify.app/ 

We decide to combine the fetching of both upcoming events and past events. But needs to display upcoming events in the order that the nearest is at the front, but keep most recent past events first as well. 

So for past events, it's DESC order, for upcoming events, it's ASC order.

**Comment by chrisguindon** [comment]
I had to revert Eric latest update to the API since we started to notice issues from the API:

- Past events were incorrectly sorted
- The live event website only had 1 event after updating the API.

@ericpoirier Can you please look at fixing your query? We reverted the version change in our make file but did not revert your patch in our module.

**Comment by ericpoirier** [comment]
> I had to revert Eric latest update to the API since we started to notice issues from the API:
> 
> * Past events were incorrectly sorted
> * The live event website only had 1 event after updating the API.
> 
> @ericpoirier Can you please look at fixing your query? We reverted the version change in our make file but did not revert your patch in our module.

I created the following patch to fix the ordering.

https://foundation.eclipse.org/r/c/drupal/custom/eclipse_api/modules/eclipse_api/+/4506

**Comment by chrisguindon** [comment]
The API changes are now live. I think we can close this now.
